[package]
name = "arith_operations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "arith_operations"
path = "src/lib.rs"

[[test]]
name = "tests"  
path = "tests" 

[dependencies]
